export const UI_ID_NAME = "maverink-ui"
export const WEBGL_WRAPPER_ID_NAME = "maverink-webgl-wrapper"
export const WEBGL_ID_NAME = "maverink-webgl"
export const IFRAME_ID_NAME = "maverink-iframe"
export const OVERLAY_ID_NAME = "maverink-overlay"